services:
  mysql:
    image: mysql:8.0
    restart: always
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: springbook
      MYSQL_USER: spring
      MYSQL_PASSWORD: book
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: book
      TZ: Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./data/mysql:/var/lib/mysql